<div class="body">
    <div class="col-md-9 col-sm-8 blog-content">

        <?php foreach ($articles as $article) : ?>

            <article class="blogpost">
                <h2 class="post-title"><a href="#"><?php echo substr($article['Titre'], 0, 20) ?></a></h2>
                <div class="post-media">
                    <img src="<?php echo $article['Image'] ?>" style="height:550px" class="img-responsive" alt="">
                </div>
                <div class="space20"></div>
                <div class="post-excerpt">
                    <p><?php echo $article['Description'] ?></p>
                </div>
                <div class="post-excerpt">
                    <p><?php echo $article['Date_Ajout'] ?></p>
                </div>
                <a href="#" class="btn-black">Read More&nbsp;&nbsp;<i class="fa fa-angle-right"></i></a>
            </article>
        <?php endforeach; ?>
        <div class="blog-sep"></div>