<!-- SLIDER -->
<div class="slider-wrap">
    <div class="tp-banner-container">


        <div class="tp-banner">
            <ul>
                <?php
                $query = 'SELECT * FROM Slider';
                $resultSet = $pdo->query($query);
                $sliders = $resultSet->fetchAll();
                ?>

                <?php foreach ($sliders as $slider) : ?>
                    <!-- SLIDE  -->
                    <li data-transition="fade" data-slotamount="2" data-masterspeed="500" data-thumb="homeslider_thumb1.jpg" data-saveperformance="on" data-title="Intro Slide">
                        <!-- MAIN IMAGE -->
                        <img src="<?php echo $slider['Image'] ?>" alt="funup" data-lazyload="<?php echo $slider['Image'] ?>" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                        <!-- LAYERS -->
                        <div class="tp-caption customin fadeout tp-resizeme rs-parallaxlevel-10" data-x="center" data-y="center" data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;" data-speed="800" data-start="1000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7300" data-endspeed="300" style="z-index: 2; max-width: 630px; max-height: 250px; background:#fff;width:100%;height:100%; white-space: nowrap;">
                        </div>


                        <!-- LAYER NR. 2 -->
                        <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9" data-x="center" data-y="250" data-speed="1000" data-start="1400" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7300" data-endspeed="1000" style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;font-family: Raleway;
                                     font-size: 36px;
                                     font-weight: bold;
                                     text-transform: uppercase;	color: #343434;"><?php echo substr($slider['T1'], 0, 7) ?><span class="ss-color" style="color:#d6644a;"><?php echo substr($slider['T1'], 7, 20) ?></span></div>
                        <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9" data-x="center" data-y="310" data-speed="1000" data-start="1800" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7300" data-endspeed="1000" style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;	font-family: Raleway;
                                     font-size: 18px;
                                     color: #333;text-align:center;">
                            <?php echo substr($slider['T2'], 0, 15) ?><br>
                            <?php echo substr($slider['T2'], 16, 30) ?>
                        </div>
                        <div class="tp-caption lft skewtoleftshort rs-parallaxlevel-9" data-x="center" data-y="375" data-speed="1000" data-start="2200" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7300" data-endspeed="1000" style="z-index: 3; max-width: 80px; max-height: 4px; width:100%;height:100%;background:#000000;"></div>
                        <a href="./categories-grid.html" class="tp-caption lft skewtoleftshort rs-parallaxlevel-9" data-x="center" data-y="395" data-speed="1000" data-start="2600" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7300" data-endspeed="1000" style="z-index: 3; max-height:100%;line-height:43px;color:#fff;font-family: Montserrat;
                                   font-size: 12px;
                                   display:table;
                                   font-weight: bold;
                                   text-transform:uppercase;padding:0 40px;background:<?php echo $slider['B_Color'] ?>;position:relative;z-index:77;">
                            <?php echo $slider['B_Txt'] ?>
                        </a>


                    </li>

                <?php endforeach; ?>
            </ul>
            <div class="tp-bannertimer"></div>
        </div>
    </div>
</div>

<!-- BLOCKS WRAP -->
<div class="block-main container">
    <?php
    $query = 'SELECT * FROM Promo';
    $resultSet = $pdo->query($query);
    $promos = $resultSet->fetchAll();
    ?>

    <?php foreach ($promos as $promo) : ?>
        <div class="row">

            <div class="col-md-4 col-sm-4">

                <div class="block-content">
                    <a href="<?php echo $promo['Url'] ?>"><img src="<?php echo $promo['Image'] ?>" style="height:520px;" class="img-responsive" alt="" />
                        <div class="bs-text-down text-center hvr-outline-out"> <?php echo $promo['T1'] ?> <span><?php echo $promo['T2'] ?></span></div>




                </div>
                </a>
            </div>

        <?php endforeach; ?>
        </div>

</div>

<div class="clearfix"></div>

<!-- FEATURED PRODUCTS -->
<div class="featured-products">
    <div class="container">
        <div class="row">
            <h5 class="heading"><span>Featured Products</span></h5>
            <ul class="filter" data-option-key="filter">
                <li><a class="selected" href="#filter" data-option-value="*">Tous les produits</a></li>
                <?php
                $query = 'SELECT * FROM Categories';
                $resultSet = $pdo->query($query);
                $cats = $resultSet->fetchAll();
                ?>

                <?php foreach ($cats as $cat) : ?>





                    <li><a href="<?= $address ?>categorie?Id=<?php echo $cat['Id'] ?>&Titre=<?php echo $cat['Titre'] ?> " data-option-value=".<?php echo $cat['Id'] ?> "><?php echo $cat['Titre'] ?></a></li>
                <?php endforeach; ?>
            </ul>


            <div id="isotope" class="isotope">

                <?php
                $query = 'SELECT * FROM Produit ';
                $resultSet = $pdo->query($query);
                $prods = $resultSet->fetchAll();
                ?>

                <?php foreach ($prods as $prod) : ?>
                    <a href="<?= $address ?>produit?id=<?php echo $prod['Id']; ?>">

                        <div class="isotope-item <?php echo $prod['Cat_Id'] ?>">
                            <div class="product-item">
                                <div class="item-thumb">
                                    <img src="<?php echo $prod['Image'] ?>" style="height:250px;" class="img-responsive" alt="" />
                                    <div class="overlay-rmore fa fa-search quickview"></div>

                                </div>
                                <div class="product-info">
                                    <h4 class="product-title"><?php echo substr($prod['Titre'], 0, 20) ?></h4>
                                    <span class="product-price"><?php echo $prod['Prix'] ?> €</span>
                                </div>
                            </div>

                        </div>
                    <?php endforeach; ?>
            </div>

        </div>
    </div>
</div>
</div>
</div>



<div class="clients">
    <div class="container">
        <div class="clearfix"></div>
        <div class="row">

            <div class="col-md-12 col-sm-12">



                <div class="clients-carousel">

                    <?php
                    $query = 'SELECT * FROM Partenaire';
                    $resultSet = $pdo->query($query);
                    $parte = $resultSet->fetchAll();
                    ?>

                    <?php foreach ($parte as $parters) : ?>

                        <div><a href="<?php echo $parters['Url']; ?>"><img src="images/<?php echo $parters['Image']; ?>" class="img-responsive" alt="" /></a></div>
                    <?php endforeach; ?>
                </div>

            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>