<div class="space10"></div>
<!-- MY ACCOUNT -->
<div class="account-wrap">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <!-- HTML -->
                <div id="account-id">
                    <h4 class="account-title"><span class="fa fa-chevron-right"></span>Connexion</h4>
                    <div class="account-form">
                        <form class="form-login" method="POST">
                            <ul class="form-list row">
                                <li class="col-md-12 col-sm-12">
                                    <label>Adresse mail <em>*</em></label>
                                    <input required type="email" class="input-text" name='Email'>
                                </li>
                                <li class="col-md-12 col-sm-12">
                                    <label>Mot de passe <em>*</em></label>
                                    <input required type="password" class="input-text" name='Pass'>
                                </li>
                            </ul>
                            <div class="buttons-set">
                                <button class="btn-black" type="submit" name="login"><span>Connexion</span></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix space20"></div>