<div class="page_header" style="height: 200px">
    <div class="container">
        <div class="page_header_info text-center" style="height: 130px">
            <div class="page_header_info_inner">
                <h2><?php echo $_GET['q'] ?></h2>
            </div>
        </div>
    </div>
</div>
<!-- SHOP CONTENT -->
<div class="shop-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-8">
               <div class="space50"></div>
                <div class="row">

                    <?php foreach ($prods as $prod) : ?>
                        <div class="col-md-4 col-sm-6">
                            <div class="product-item">
                                <div class="item-thumb">
                                    <center><img src="<?php echo $prod['Image'] ?>" style="height:200px;" class="img-responsive" alt="" /></center>
                                </div>
                                <div class="product-info">
                                    <h4 class="product-title"><a href="<?= $address ?>produit?id=<?php echo $prod['Id']; ?>"
                                    <h4 class="product-title"><?php echo substr($prod['Titre'], 0, 20) ?></h4>
                                            <span class=" product-price"><?php echo $prod['Prix'] ?> €</span>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix space20"></div>

