<?php

if (isset($_GET['q'])) {

    $query =
        '  
       INSERT INTO
       Recherche
       (Txt,DateR,User_Id)
       VALUES
       (?,NOW(),?)
    ';
    if (!isset($_SESSION['user_id'])) {
        $res = 0;
    } else {
        $res = $_SESSION['user_id'];
    }
    $resultSet = $pdo->prepare($query);
    $resultSet->execute([$_GET['q'], $res]);
}
?>


<!-- PAGE HEADER -->
<div class="page_header" style="height: 200px">
    <div class="container">
        <div class="page_header_info text-center" style="height: 130px">
            <div class="page_header_info_inner">
                <h2><?php echo $_GET['q'] ?></h2>

            </div>
        </div>
    </div>
</div>


<!-- SHOP CONTENT -->
<div class="shop-content">
    <div class="container">





        <div class="row">

            <div class="col-md-12 col-sm-8">


                <div class="space50"></div>

                <div class="row">
                    <?php
                    $query = "SELECT * FROM Produit WHERE Titre LIKE '%" . $_GET['q'] . "%'";
                    $resultSet = $pdo->query($query);
                    $prods = $resultSet->fetchAll();
                    ?>

                    <?php foreach ($prods as $prod) : ?>



                        <div class="col-md-4 col-sm-6">
                            <div class="product-item">
                                <div class="item-thumb">
                                    <center><img src="<?php echo $prod['Image'] ?>" style="height:200px;" class="img-responsive" alt="" /></center>

                                </div>
                                <div class="product-info">
                                    <h4 class="product-title"><a href="./produit.php?id=<?php echo ($prod['Id']); ?>><?php echo substr($prod['Titre'], 0, 20) ?></a></h4>
                                            <span class=" product-price"><?php echo $prod['Prix'] ?> €</span>

                                </div>
                            </div>

                        </div>
                    <?php endforeach; ?>
                </div>


            </div>

        </div>


    </div>

</div>

<div class="clearfix space20"></div>

<?php include('footer.php'); ?>



<!-- Javascript -->
<script src="js/jquery.js"></script>

<!-- ADDTHIS -->
<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557a95e76b3e51d9" async="async"></script>
<script type="text/javascript">
    // Call this function once the rest of the document is loaded
    function loadAddThis() {
        addthis.init()
    }
</script>
<script src="js/bootstrap.min.js"></script>
<script src="plugin/owl-carousel/owl.carousel.min.js"></script>
<script src="js/bs-navbar.js"></script>
<script src="js/vendors/isotope/isotope.pkgd.js"></script>
<script src="js/vendors/slick/slick.min.js"></script>
<script src="js/vendors/tweets/tweecool.min.js"></script>
<script src="js/vendors/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<script src="js/vendors/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
<script src="js/jquery.sticky.js"></script>
<script src="js/jquery.subscribe-better.js"></script>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="js/vendors/select/jquery.selectBoxIt.min.js"></script>
<script src="js/main.js"></script>

</body>

</html>