<div class="body">
    <div class="shop-single shopping-cart">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <table class="cart-table">
                        <tr>
                            <th>Supprimer</th>
                            <th>Image</th>
                            <th>Produit</th>
                            <th>Quantité</th>
                            <th>P.U</th>
                            <th>Total</th>
                        </tr>
                        <?php
                        for ($i = 0; $i < count($_SESSION['panier']['idProduit']); $i++) {
                            $query = 'SELECT * FROM Produit WHERE Id=?';
                            $resultSet = $pdo->prepare($query);
                            $resultSet->execute([$_SESSION['panier']['idProduit'][$i]]);
                            $tempproduit = $resultSet->fetch();

                        ?>
                            <tr>
                                <td><a href="<?= $address ?>panier?del=<?php echo $_SESSION['panier']['idProduit'][$i] ?>"><i class="fa fa-trash-o"></i></a></td>
                                <td><img src="<?php echo $tempproduit['Image']; ?>" class="img-responsive" alt="" /></td>
                                <td>
                                    <h4><a href="<?= $address ?>produit"><?php echo $_SESSION['panier']['libelleProduit'][$i] ?></a></h4>
                                </td>
                                <td><?php echo compterArticles(); ?></td>
                                <!--mettre ici la qte-->
                                <td>
                                    <div class="item-price"><?php echo $_SESSION['panier']['prixProduit'][$i] ?> €</div><!-- mettre ici le PU-->
                                </td>
                                <td>
                                    <div class="item-price"><?php echo $_SESSION['panier']['qteProduit'][$i] * $_SESSION['panier']['prixProduit'][$i] ?>€</div><!-- mettre ici le Total-->
                                </td>

                            </tr>
                        <?php } ?>
                    </table>
                    <div class="clearfix space20"></div>
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="totals">
                            <table id="shopping-cart-totals-table">
                                <tfoot>
                                    <tr>
                                        <td class="a-right" colspan="1">
                                            <strong>Total</strong>
                                        </td>
                                        <td class="a-right">
                                            <strong><span class="price"><?php echo MontantGlobal(); ?> €</span></strong>
                                        </td>
                                        <td class="a-right">
                                            <ul class="checkout-types">
                                                <li class="space10"><button type="button" class="btn-color">Paiement</button></li>
                                            </ul>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
